/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.oficina.telas;

import java.text.DateFormat;
import java.util.Date;
import java.sql.*;
import br.com.oficina.dal.ModuloConexao;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jorgecosta
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs   = null;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblData = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        lblUser = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuCad = new javax.swing.JMenu();
        MenuCadUsu = new javax.swing.JMenuItem();
        MenuCadOs = new javax.swing.JMenuItem();
        MenuCadVeic = new javax.swing.JMenuItem();
        MenuRel = new javax.swing.JMenu();
        MenuRelServ = new javax.swing.JMenuItem();
        MenuRelFrota = new javax.swing.JMenuItem();
        MenuPesq = new javax.swing.JMenu();
        MenuPesOs = new javax.swing.JMenuItem();
        MenuPesFrota = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuAjuSob = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para Controle Oficina");
        setBackground(new java.awt.Color(120, 131, 141));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblData.setText("DATA");

        Desktop.setBackground(new java.awt.Color(175, 189, 203));
        Desktop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Desktop.setOpaque(false);

        lblUser.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblUser.setText("Usuario");
        lblUser.setPreferredSize(new java.awt.Dimension(640, 480));

        MenuCad.setText("Cadastro");

        MenuCadUsu.setText("Usuario");
        MenuCadUsu.setEnabled(false);
        MenuCad.add(MenuCadUsu);

        MenuCadOs.setText("OS");
        MenuCad.add(MenuCadOs);

        MenuCadVeic.setText("Veiculo");
        MenuCad.add(MenuCadVeic);

        Menu.add(MenuCad);

        MenuRel.setText("Relatorio");
        MenuRel.setEnabled(false);

        MenuRelServ.setText("Servicos");
        MenuRel.add(MenuRelServ);

        MenuRelFrota.setText("Frota");
        MenuRel.add(MenuRelFrota);

        Menu.add(MenuRel);

        MenuPesq.setText("Pesquisar");

        MenuPesOs.setText("OS");
        MenuPesq.add(MenuPesOs);

        MenuPesFrota.setText("Frota");
        MenuPesq.add(MenuPesFrota);

        Menu.add(MenuPesq);

        jMenu1.setText("Ajuda");

        MenuAjuSob.setText("Sobre");
        jMenu1.add(MenuAjuSob);

        Menu.add(jMenu1);

        MenuSair.setText("Sair");
        Menu.add(MenuSair);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(782, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Codigo para mostrar a data na tela principal.
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem MenuAjuSob;
    private javax.swing.JMenu MenuCad;
    private javax.swing.JMenuItem MenuCadOs;
    public static javax.swing.JMenuItem MenuCadUsu;
    private javax.swing.JMenuItem MenuCadVeic;
    private javax.swing.JMenuItem MenuPesFrota;
    private javax.swing.JMenuItem MenuPesOs;
    private javax.swing.JMenu MenuPesq;
    public static javax.swing.JMenu MenuRel;
    private javax.swing.JMenuItem MenuRelFrota;
    private javax.swing.JMenuItem MenuRelServ;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
